/**
 * Generated by github copilot.
 * @param {object} o 
 * @returns fattened json
 */
export function flattenJson(o) {
    var result = {};
    function recurse(cur, prop) {
        if (Object(cur) !== cur) {
            result[prop] = cur;
        } else if (Array.isArray(cur)) {
            for (var i = 0, l = cur.length; i < l; i++) {
                recurse(cur[i], prop + "[" + i + "]");
            }
        if (l === 0) {
            result[prop] = [];
        }
        } else {
            var isEmpty = true;
            for (var p in cur) {
                isEmpty = false;
                recurse(cur[p], prop ? prop + "." + p : p);
            }
            if (isEmpty) {
                result[prop] = {};
            }
        }
    }
    recurse(o, "");
    return result;
}
